# In users/urls.py

from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (
    UserRegistrationView,
    UserProfileView,
    UserAccountView,
    CalorieGoalSuggestionViewSet
)

# Create a router only for the ViewSet
router = DefaultRouter()
router.register(r'calorie-suggestions', CalorieGoalSuggestionViewSet, basename='calorie-suggestion')

urlpatterns = [
    # Path for new user registration
    path('register/', UserRegistrationView.as_view(), name='user-register'),
    
    # Path for viewing and updating the user's fitness profile
    path('profile/', UserProfileView.as_view(), name='user-profile'),
    
    # Path for viewing and updating the user's account details
    path('account/', UserAccountView.as_view(), name='user-account'),
    
    # Include the URLs generated by the router for the calorie suggestions
    path('', include(router.urls)),
]