# Generated by Django 5.2.4 on 2025-08-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="total_calories",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name="fooditem",
            name="calories",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="fooditem",
            name="carbs",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="fooditem",
            name="fats",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="fooditem",
            name="protein",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="mealitem",
            name="quantity_g",
            field=models.DecimalField(
                decimal_places=2, help_text="Quantity in grams", max_digits=8
            ),
        ),
    ]
