# Generated by Django 5.2.4 on 2025-08-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="profile_picture",
        ),
        migrations.AddField(
            model_name="profile",
            name="calorie_goal",
            field=models.CharField(
                blank=True,
                choices=[
                    ("deficit", "Calorie Deficit"),
                    ("surplus", "Calorie Surplus"),
                    ("maintain", "Maintain Weight"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
