# Generated by Django 5.2.4 on 2025-08-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_profile_profile_picture_profile_calorie_goal"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="daily_calorie_intake",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
