# Generated by Django 5.2.4 on 2025-08-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_profile_age_profile_daily_calorie_intake"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="daily_calorie_intake",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
    ]
