# Generated by Django 5.2.4 on 2025-08-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_profile_daily_calorie_intake"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="calorie_goal",
        ),
        migrations.AddField(
            model_name="profile",
            name="activity_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sedentary", "Sedentary (little or no exercise)"),
                    ("lightly_active", "Lightly active (1-3 days/week)"),
                    ("moderately_active", "Moderately active (3-5 days/week)"),
                    ("very_active", "Very active (6-7 days/week)"),
                    (
                        "extra_active",
                        "Extra active (very hard exercise & physical job)",
                    ),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="calorie_goal_option",
            field=models.CharField(
                blank=True,
                choices=[
                    ("deficit", "Calorie Deficit"),
                    ("surplus", "Calorie Surplus"),
                    ("maintain", "Maintain Weight"),
                ],
                help_text="The user's primary goal (lose, gain, or maintain weight).",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female")],
                max_length=10,
                null=True,
            ),
        ),
    ]
